Repository depromeet/ygtang-app, pull requests merged in 2022-05, with the labels that each got.

#21 webview 추가 및 safe area 설정
  .github/CODEOWNERS
  App.tsx
  android/app/src/main/java/com/ygt/MainApplication.java
  android/settings.gradle
  ios/Podfile
  ios/Podfile.lock
  ios/ygt.xcodeproj/project.pbxproj
  ios/ygt.xcodeproj/xcshareddata/xcschemes/ygt.xcscheme
  ios/ygt.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  package.json
  yarn.lock
Labels: feat

#23 app icon 추가 - Android, iOS
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  ios/ygt/Images.xcassets/AppIcon.appiconset/1024.png
  ios/ygt/Images.xcassets/AppIcon.appiconset/Contents.json
  ios/ygt/Images.xcassets/AppIcon.appiconset/android-icon-40x40.png
  ios/ygt/Images.xcassets/AppIcon.appiconset/android-icon-87x87.png
  ios/ygt/Images.xcassets/AppIcon.appiconset/apple-icon-120x120-1.png
  ios/ygt/Images.xcassets/AppIcon.appiconset/apple-icon-120x120.png
  ios/ygt/Images.xcassets/AppIcon.appiconset/apple-icon-180x180.png
  ios/ygt/Images.xcassets/AppIcon.appiconset/apple-icon-58x58.png
  ios/ygt/Images.xcassets/AppIcon.appiconset/apple-icon-60x60.png
  ios/ygt/Images.xcassets/AppIcon.appiconset/favicon-80x80.png
Labels: env, feat

#26 앱 내 링크 썸네일 클릭 시 새 창으로 열리지 않는 에러 해결
  src/screens/HomeScreen.tsx
Labels: fix

#31 외부 링크 디스플레이 문제 해결
  ios/Podfile.lock
  src/screens/HomeScreen.tsx
Labels: fix

#37 onShouldStartLoadWithRequest ios일 경우, 명시적으로 클릭했을때만 외부링크 열기
  src/screens/HomeScreen.tsx
Labels: fix
