Repository depromeet/ygtang-app, pull requests merged in 2022-06, with the labels that each got.

#33 안드로이드 dom storage 활성화
  src/screens/HomeScreen.tsx
Labels: fix

#43 스플래시 화면 추가 및 screen animation 수정
  App.tsx
  ios/Podfile.lock
  ios/ygt/LaunchScreen.storyboard
  src/assets/ygt-splash.json
  src/navigation/MainNavigator.tsx
  src/screens/HomeScreen.tsx
  src/screens/SplashScreen.tsx
  src/styles/theme.ts
Labels: design, feat

#47 splash design 변경 및 launch screen 색상 수정
  ios/ygt/LaunchScreen.storyboard
  src/screens/SplashScreen.tsx
  src/styles/theme.ts
Labels: design, :zap:

#49 IOS - 카메라 및 앨범 접근 권한 추가
  ios/ygt/Info.plist
Labels: env

#55 iOS app name 수정
  app.json
Labels: feat, :zap:

#58 splash icon 사이즈 수정
  src/screens/SplashScreen.tsx
Labels: design, :zap:

#59 fix: 안쓰는 권한 삭제 및 언어 한국어로 변경
  ios/ygt/Info.plist
Labels: env

#50 안드로이드 앱 이름 변경 (label)
  android/app/src/main/res/values/strings.xml
Labels: feat, :zap:

#54 안드로이드의 버전 코드 수정
  android/app/build.gradle
Labels: feat, :zap:

#61 권한 설명 길게 설정
  app.json
  ios/ygt/Info.plist
Labels: env

#65 안드로이드 status bar 안보이는 이슈 수정
  android/app/src/main/res/values/styles.xml
  src/screens/HomeScreen.tsx
Labels: fix

#67 docs: readme 추가
  README.md
Labels: docs

#68 edit: splash duration 2000 설정
  src/screens/SplashScreen.tsx
Labels: design

#70 네트워크 오류 시 에러 페이지 보여주기
  src/assets/error_character.png
  src/components/Button.tsx
  src/components/Error.tsx
  src/screens/HomeScreen.tsx
Labels: feat

#71 iOS 제스처 옵션 추가
  src/screens/HomeScreen.tsx
Labels: feat, :zap:

#74 IOS 버전 및 package 버전 업
  ios/ygt.xcodeproj/project.pbxproj
  ios/ygt/Info.plist
  package.json
Labels: chore

#73 안드로이드 버전 업
  android/app/build.gradle
Labels: chore

#78 edit: splash에서 home으로 전환 시 하얀색 깜빡임 제거
  App.tsx
  package.json
  src/navigation/MainNavigator.tsx
  src/screens/HomeScreen.tsx
  src/screens/SplashScreen.tsx
  yarn.lock
Labels: fix

#82 공유 커스텀 뷰 - 공유 데이터 contentType 전달
  src/components/Share.tsx
Labels: feat

#80 safe area 원복 및 하단 safe area 제거
  src/components/YgtStatusBar.tsx
  src/screens/HomeScreen.tsx
Labels: fix

#90 IOS - Refresh 토큰 ShareExtension과 공유하기
  .eslintrc.js
  ios/Podfile
  ios/Podfile.lock
  ios/ShareExtention/ShareExtention.entitlements
  ios/ygt/ygt.entitlements
  ios/ygt/ygtRelease.entitlements
  package.json
  src/components/Share.tsx
  src/constants/common.ts
  src/hooks/useShareWebToken.ts
  src/screens/HomeScreen.tsx
  yarn.lock
Labels: dependencies, feat

#88 feat: 안드로이드 백 버튼 핸들링, 웹뷰 리팩토링
  src/components/Share.tsx
  src/components/ShareHandler.tsx
  src/components/WebView.tsx
  src/screens/HomeScreen.tsx
Labels: fix, refactor

#98 리드미 이미지, 소개글, 뱃지 업데이트
  README.md
Labels: docs

#100 react-native bump up to 0.68.2
  ios/ygt.xcodeproj/project.pbxproj
  package.json
  yarn.lock
Labels: env

#101 Improper Neutralization of Special Elements used in a Command in Shell-quote
  ios/Podfile.lock
  yarn.lock
Labels: bug

#105 IOS 1.1.0 배포
  index.js
  index.share.js
  ios/Podfile
  ios/Podfile.lock
  ios/ShareExtention/Info.plist
  ios/ygt.xcodeproj/project.pbxproj
  package.json
  src/components/Share.tsx
  yarn.lock
Labels: env, dependencies, feat

#111 안드로이드에서 공유 기능 나갈 시 Share 컴포넌트 해제 처리하기
  src/components/ShareHandler.tsx
  src/constants/common.ts
  src/hooks/useWebViewNavigateWrapping.ts
Labels: feat

#114 안드로이드 버전 업 (1.1.1-android.1)
  android/app/build.gradle
Labels: chore
