Repository depromeet/ygtang-app, pull requests merged in 2022-11, with the labels that each got.

#129 안드로이드 빌드 이슈 해결 및 버전 업
  android/app/build.gradle
  android/build.gradle
  package.json
  yarn.lock
Labels: fix

#123 clipboard로 영감 추가하기 기능
  ios/Podfile.lock
  ios/ygt.xcodeproj/project.pbxproj
  ios/ygt.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  ios/ygt.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  package.json
  src/components/ClipboardMessenger.tsx
  src/constants/common.ts
  src/screens/HomeScreen.tsx
  yarn.lock
Labels: feat

#130 chore: 안드로이드 버전 코드 업
  android/app/build.gradle
Labels: :zap:, chore, platform: Android

#132 fix: 모바일 공유하기 네트워크 오류
  package.json
  src/constants/common.ts
Labels: bug

#133 안드로이드 버전 배포 대응 v1.2.2
  android/app/build.gradle
  package.json
Labels: enhancement
