Repository depromeet/ygtang-app, pull requests merged in 2023-02, with the labels that each got.

#139 에러 로그 수집 sentry 적용하기
  .gitignore
  App.tsx
  android/app/build.gradle
  android/app/src/main/java/kr/ygtang/MainActivity.java
  android/app/src/main/java/kr/ygtang/MainApplication.java
  android/app/src/main/java/kr/ygtang/newarchitecture/MainApplicationReactNativeHost.java
  android/app/src/main/java/kr/ygtang/newarchitecture/components/MainComponentsRegistry.java
  android/app/src/main/java/kr/ygtang/newarchitecture/modules/MainApplicationTurboModuleManagerDelegate.java
  android/settings.gradle
  ios/Podfile
  ios/Podfile.lock
  ios/ygt.xcodeproj/project.pbxproj
  ios/ygt.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  package.json
  src/components/Share.tsx
  src/components/ShareHandler.tsx
  src/screens/HomeScreen.tsx
  src/utils/sentry/index.ts
  src/utils/sentry/sentry.ts
  yarn.lock
Labels: enhancement

#141 webview postMessage JSON.parse에러 해결
  ios/ShareExtention/Info.plist
  ios/ygt.xcodeproj/project.pbxproj
  ios/ygt/Info.plist
  src/components/Share.tsx
  src/components/ShareHandler.tsx
  src/screens/HomeScreen.tsx
Labels: bug

#142 chore: version을 1.2.3 변경
  android/app/build.gradle
  package.json
Labels: chore

#144 inactive 웹뷰 로드 핸들링
  src/components/WebView.tsx
Labels: fix, platform: iOS
